// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAivKsjSC9zR49GCY8RKQsayvzQkLNvrYk',
    appId: '1:911576985036:web:8e7d15ce492c6195148169',
    messagingSenderId: '911576985036',
    projectId: 'gerenteappclaudio-e148d',
    authDomain: 'gerenteappclaudio-e148d.firebaseapp.com',
    storageBucket: 'gerenteappclaudio-e148d.appspot.com',
    measurementId: 'G-33EHJB3FJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3DOBMTK0DdUbLDiiIzTz_o5xft5-DtcQ',
    appId: '1:911576985036:android:94e5be681ec6d0e2148169',
    messagingSenderId: '911576985036',
    projectId: 'gerenteappclaudio-e148d',
    storageBucket: 'gerenteappclaudio-e148d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxxHOlWpZO_DQ71iRjym98uGsC6szLRD0',
    appId: '1:911576985036:ios:954d8a16e96724cf148169',
    messagingSenderId: '911576985036',
    projectId: 'gerenteappclaudio-e148d',
    storageBucket: 'gerenteappclaudio-e148d.appspot.com',
    iosClientId: '911576985036-m608iucm1mg08140q0odr3csrtn27m96.apps.googleusercontent.com',
    iosBundleId: 'com.example.gerenteDeApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxxHOlWpZO_DQ71iRjym98uGsC6szLRD0',
    appId: '1:911576985036:ios:77fe97f75ded858d148169',
    messagingSenderId: '911576985036',
    projectId: 'gerenteappclaudio-e148d',
    storageBucket: 'gerenteappclaudio-e148d.appspot.com',
    iosClientId: '911576985036-tdaistkpu4qa8nb88oefdn1f2mp9nbf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gerenteDeApps.RunnerTests',
  );
}
